
---
fixtures:
  symlinks:
    profile: "#{source_dir}/site/profile"
    role: "#{source_dir}/site/role"
  forge_modules:
    stdlib:
      repo: puppetlabs-stdlib
      ref: 4.16.0
    apt:
      repo: puppetlabs-apt
      ref: 2.4.0
    inifile:
      repo: puppetlabs-inifile
      ref: 1.6.0
    node_manager:
      repo: WhatsARanjit-node_manager
      ref: 0.4.1
    pe_gem:
      repo: puppetlabs-pe_gem
      ref: 0.2.0
    haproxy:
      repo: puppetlabs-haproxy
      ref: 1.5.0
    concat:
      repo: puppetlabs-concat
      ref: 2.2.1
    gitlab:
      repo: vshn-gitlab
      ref: 1.13.3
    jenkins:
      repo: rtyler-jenkins
      ref: 1.7.0
    java:
      repo: puppetlabs-java
      ref: 1.6.0
    zypprepo:
      repo: darin-zypprepo
      ref: 1.0.2
    archive:
      repo: puppet-archive
      ref: 1.3.0
    puppet_agent_settings:
      repo: laura-puppet_agent_settings
      ref: 0.1.1
    sudo:
      repo: saz-sudo
      ref: 4.1.0
    ssh:
      repo: saz-ssh
      ref: 3.0.1
