---
sudo: false
language: ruby
bundler_args: --without system_tests
script: "bundle exec onceover run spec"
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.3
    env: PUPPET_GEM_VERSION="> 5.0.0"
notifications:
  email: false
