forge "http://forge.puppetlabs.com"

mod 'puppetlabs/stdlib', '4.16.0'
mod 'puppetlabs/apt', '2.4.0'
mod 'puppetlabs/inifile', '1.6.0'
mod 'WhatsARanjit/node_manager', '0.4.1'
mod 'puppetlabs/pe_gem', '0.2.0'
mod 'puppetlabs/haproxy', '1.5.0'
mod 'puppetlabs/concat', '2.2.1'
mod 'vshn/gitlab', '1.13.3'
mod 'rtyler/jenkins', '1.7.0'
mod 'puppetlabs/java', '1.6.0'
mod 'darin/zypprepo', '1.0.2'
mod 'puppet/archive', '1.3.0'
mod 'laura/puppet_agent_settings', '0.1.1'
mod 'saz/sudo', '4.1.0'
